default[:ffmpeg][:dependencies] = "dependencies"
default[:ffmpeg][:install_method] = "source"
default[:ffmpeg][:source_path] = "/root/ffmpeg_sources"
default[:ffmpeg][:version] = "3.1"
default[:ffmpeg][:source_url] = "http://ffmpeg.org/releases/ffmpeg-#{default[:ffmpeg][:version]}.tar.gz"
default[:ffmpeg][:source_prefix] = "/opt"